//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Data.DataTable GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNameStudSelectData", ReplyAction="http://tempuri.org/IService1/GetNameStudSelectDataResponse")]
        System.Data.DataTable GetNameStudSelectData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNameStudSelectData", ReplyAction="http://tempuri.org/IService1/GetNameStudSelectDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetNameStudSelectDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDisSelectData", ReplyAction="http://tempuri.org/IService1/GetDisSelectDataResponse")]
        System.Data.DataTable GetDisSelectData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDisSelectData", ReplyAction="http://tempuri.org/IService1/GetDisSelectDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDisSelectDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecCheck", ReplyAction="http://tempuri.org/IService1/RecCheckResponse")]
        string RecCheck(string id_dis, string id_stud, string date, string ocenka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecCheck", ReplyAction="http://tempuri.org/IService1/RecCheckResponse")]
        System.Threading.Tasks.Task<string> RecCheckAsync(string id_dis, string id_stud, string date, string ocenka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertMethod", ReplyAction="http://tempuri.org/IService1/InsertMethodResponse")]
        string InsertMethod(string id_stud, string id_dis, string date, string mark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertMethod", ReplyAction="http://tempuri.org/IService1/InsertMethodResponse")]
        System.Threading.Tasks.Task<string> InsertMethodAsync(string id_stud, string id_dis, string date, string mark);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.ServiceReference1.IService1>, Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public System.Data.DataTable GetNameStudSelectData() {
            return base.Channel.GetNameStudSelectData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetNameStudSelectDataAsync() {
            return base.Channel.GetNameStudSelectDataAsync();
        }
        
        public System.Data.DataTable GetDisSelectData() {
            return base.Channel.GetDisSelectData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDisSelectDataAsync() {
            return base.Channel.GetDisSelectDataAsync();
        }
        
        public string RecCheck(string id_dis, string id_stud, string date, string ocenka) {
            return base.Channel.RecCheck(id_dis, id_stud, date, ocenka);
        }
        
        public System.Threading.Tasks.Task<string> RecCheckAsync(string id_dis, string id_stud, string date, string ocenka) {
            return base.Channel.RecCheckAsync(id_dis, id_stud, date, ocenka);
        }
        
        public string InsertMethod(string id_stud, string id_dis, string date, string mark) {
            return base.Channel.InsertMethod(id_stud, id_dis, date, mark);
        }
        
        public System.Threading.Tasks.Task<string> InsertMethodAsync(string id_stud, string id_dis, string date, string mark) {
            return base.Channel.InsertMethodAsync(id_stud, id_dis, date, mark);
        }
    }
}
